# Generated by Django 5.1.1 on 2024-09-16 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNumber', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(max_length=5)),
            ],
        ),
    ]
