# Generated by Django 5.1.1 on 2024-09-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataentery', '0002_alter_student_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='rollNumber',
            new_name='roll_no',
        ),
    ]
