# Generated by Django 5.1.1 on 2024-09-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentery', '0003_rename_rollnumber_student_roll_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(max_length=5, primary_key=True, serialize=False, unique=True),
        ),
    ]
